import { storage } from "./storage";
import type { InsertProduct } from "@shared/schema";

export async function seedProducts() {
  const products: InsertProduct[] = [
    {
      partId: "ENG-001",
      type: "engine",
      year: 2022,
      make: "Ford",
      model: "F-150",
      details: "5.0L V8 Coyote Engine - Low Mileage",
      price: 450000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/engine-1.jpg",
      protection: "90-Day Return",
      location: "Texas Warehouse",
      description: "Tested and verified performance engine.",
    },
    {
      partId: "TRN-002",
      type: "transmission",
      year: 2021,
      make: "Chevrolet",
      model: "Silverado",
      details: "10-Speed Automatic Transmission",
      price: 280000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/transmission-1.jpg",
      protection: "90-Day Return",
      location: "Florida Hub",
      description: "Smooth shifting transmission, fully inspected.",
    },
    {
      partId: "CHS-003",
      type: "chassis",
      year: 2023,
      make: "Toyota",
      model: "Tacoma",
      details: "Reinforced Chassis Plate - OEM Standard",
      price: 45000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/chassis-1.jpg",
      protection: "90-Day Return",
      location: "California Center",
      description: "High-grade steel chassis plate for heavy duty use.",
    },
    {
      partId: "ENG-004",
      type: "engine",
      year: 2020,
      make: "Honda",
      model: "Civic Type R",
      details: "2.0L Turbocharged K20C1 Engine",
      price: 520000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/engine-1.jpg",
      protection: "90-Day Return",
      location: "Georgia Warehouse",
      description: "High performance racing engine in excellent condition.",
    },
    {
      partId: "TRN-005",
      type: "transmission",
      year: 2019,
      make: "BMW",
      model: "3 Series",
      details: "ZF 8HP Automatic Transmission",
      price: 320000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/transmission-1.jpg",
      protection: "90-Day Return",
      location: "New York Hub",
      description: "Precision engineered ZF transmission for luxury performance.",
    },
    {
      partId: "AXL-006",
      type: "axle",
      year: 2021,
      make: "Ford",
      model: "Super Duty",
      details: "Dana 60 Front Axle Assembly",
      price: 180000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/axle-1.jpg",
      protection: "90-Day Return",
      location: "Arizona Warehouse",
      description: "Heavy duty axle for towing and off-road applications.",
    },
    {
      partId: "DIF-007",
      type: "differential",
      year: 2022,
      make: "Jeep",
      model: "Wrangler",
      details: "Tru-Lok Electronic Locking Differential",
      price: 85000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/differential-1.jpg",
      protection: "90-Day Return",
      location: "Colorado Hub",
      description: "Genuine Jeep locking differential for ultimate traction.",
    },
    {
      partId: "ENG-008",
      type: "engine",
      year: 2018,
      make: "Toyota",
      model: "Camry",
      details: "2.5L 4-Cylinder A25A-FKS Engine",
      price: 195000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/engine-1.jpg",
      protection: "90-Day Return",
      location: "Texas Warehouse",
      description: "Reliable Toyota engine with low verified miles.",
    },
    {
      partId: "AXL-009",
      type: "axle",
      year: 2020,
      make: "RAM",
      model: "2500",
      details: "Rear Axle Assembly - 11.5 inch Ring Gear",
      price: 215000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/axle-1.jpg",
      protection: "90-Day Return",
      location: "Ohio Warehouse",
      description: "Heavy duty rear axle for RAM trucks.",
    },
    {
      partId: "TRN-010",
      type: "transmission",
      year: 2017,
      make: "Nissan",
      model: "Altima",
      details: "CVT Transmission Assembly",
      price: 145000,
      status: "In Stock",
      customer: "Pending",
      imageUrl: "/images/transmission-1.jpg",
      protection: "90-Day Return",
      location: "Nevada Hub",
      description: "Genuine Nissan CVT transmission, low miles.",
    },
  ];

  for (const product of products) {
    await storage.createProduct(product);
  }

  console.log(`✅ Seeded ${products.length} products`);
}
